GlobalPlanner:
  allow_unknown: false
  default_tolerance: 0.08 #0.05-------
  visualize_potential: true
  use_dijkstra: true
  use_quadratic: true
  use_grid_path: false
  old_navfn_behavior: false

  lethal_cost: 240
  neutral_cost: 66
  cost_factor: 0.55
  publish_potential: true
  orientation_mode: 0
  orientation_window_size: 1
