TebLocalPlannerROS:

  odom_topic: /Odometry
  # Trajectory
  teb_autosize: True
  dt_ref: 0.44
  dt_hysteresis: 0.044
  min_samples: 4 # default
  global_plan_overwrite_orientation: True
  global_plan_viapoint_sep: 0.1  # not fine-tuned
  allow_init_with_backwards_motion: False
  max_global_plan_lookahead_dist: 3
  feasibility_check_no_poses: 5
  exact_arc_length: True

  # Robot
  max_vel_x: 5
  max_vel_x_backwards: 4.4
  max_vel_y: 11 # for omnidirection
  max_vel_theta: 3.5 #0.5------
  acc_lim_x: 4.6
  acc_lim_y: 6.3 # for omnidirection
  acc_lim_theta: 3.14

  is_footprint_dynamic: False
  min_turning_radius: 0.0 # diff-drive robot (can turn on place!)
  wheelbase: 0.0

  footprint_model:
    type: "polygon"
    vertices: [[-0.14, -0.14], [-0.14, 0.14], [0.14, 0.14], [0.14, -0.14]] # 2D shape of the robot

  # GoalTolerance    
  xy_goal_tolerance: 0.02 #0.15------
  yaw_goal_tolerance: 0.035 #0.06------
  free_goal_vel: False
    
  # Obstacles    
  min_obstacle_dist: 0.09 # 0.05 # a small value may be prefered
  include_costmap_obstacles: True
  costmap_obstacles_behind_robot_dist: 1.0
  obstacle_poses_affected: 30
  costmap_converter_plugin: "line"
  costmap_converter_spin_thread: True
  costmap_converter_rate: 1
  inflaion_dist: 0.18 # not fine-tuned

  # Optimization
  no_inner_iterations: 4 # may be enough
  no_outer_iterations: 4 # may be enough
  optimization_activate: True
  optimization_verbose: False
  penalty_epsilon: 0.12
  weight_max_vel_x: 6
  weight_max_vel_y: 6
  weight_max_vel_theta: 3 #0.2-------
  weight_acc_lim_x: 3
  weight_acc_lim_y: 3
  weight_acc_lim_theta: 3
  weight_kinematics_nh: 0.01 # for omnidirection, a small value is preferred
  weight_kinematics_forward_drive: 0.0 #1.0------
  weight_kinematics_turning_radius: 0.0
  weight_optimaltime: 8 # not fine-tuned
  weight_shortest_path: 0.9 # not fine-tuned
  weight_obstacle: 53
  weight_dynamic_obstacle: 10 # not in use yet
  weight_adapt_factor: 1
  weight_inflation: 1.3 # not fine-tuned
  weight_viapoint: 1.0 # default

  # Homotopy Class Planner
  enable_homotopy_class_planning: False
  enable_multithreading: False
  simple_exploration: False
  max_number_classes: 2
  selection_cost_hysteresis: 1.0
  selection_obst_cost_scale: 1.0
  selection_alternative_time_cost: False

  roadmap_graph_no_samples: 15
  roadmap_graph_area_width: 5
  h_signature_prescaler: 0.5
  h_signature_threshold: 0.1
  obstacle_keypoint_offset: 0.1
  obstacle_heading_threshold: 0.45
  visualize_hc_graph: True
