local_costmap:
  global_frame: init
  robot_base_frame: base_link

  update_frequency: 5.0
  publish_frequency: 5.0

  transform_tolerance: 0.3

  rolling_window: true
  width: 5.0
  height: 5.0
 
  origin_x: 0
  origin_y: 0  
  
  plugins:
    - {name: obstacle_layer,  type: "costmap_2d::ObstacleLayer"}
    - {name: static_layer,    type: "costmap_2d::StaticLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

  inflation_layer: 
    enabled: true
    cost_scaling_factor: 16.2 #5.0-- # a small value is preferred
    inflation_radius: 0.22  #0.20--     # a small value is preferred

